# GTNH Buildscript configuration
modName = Modular Routers
modId = modularrouters
modGroup = me.desht.modularrouters

# Minecraft/Forge
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614

# MCP Mappings
channel = stable
mappingsVersion = 12
remoteMappings = https://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

# Development
developmentEnvironmentUserName = Developer
enableModernJavaSyntax = true
enableGenericInjection = true

# Version
generateGradleTokenClass = me.desht.modularrouters.Tags
gradleTokenVersion = VERSION

# Features
usesMixins = false
usesShadowedDependencies = false

# Repositories
includeWellKnownRepositories = true

# Publishing
usesMavenPublishing = false
autoUpdateBuildScript = false
